services:
  rust_devcontainer:
    image: rust:latest
    restart: always
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: rust_devcontainer_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/init.sql 
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_devcontainer_db
    ports:
      - "5432:5432"